name: Deploy Top Movies Data

on:
  schedule:
    # Runs at 7:50 AM UTC every day
    - cron: '50 7 * * *'
  workflow_dispatch:  # Allows you to run this workflow manually from the Actions tab

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Specify the Python version you are using

    - name: Install Dependencies
      run: |
        pip install requests beautifulsoup4 pandas  # Replace with your actual dependencies

    - name: Run Python Script
      run: python movie_scrapper.py  # Replace with the path to your script

    - name: Commit and Push if Changes
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add docs/index.html  # Add the file you want to commit, including the correct path
        git commit -m "Update top movies data" -a || echo "No changes to commit"
        git push || echo "No changes to push"
